/**
 * Resolves the lead-intake Function URL.
 *
 * Order of resolution:
 *   1. `VITE_LEAD_INTAKE_URL` env var (set in `.env.local` or Amplify Hosting)
 *   2. `amplify_outputs.json` — generated by `npx ampx sandbox` or by an
 *      Amplify Hosting deploy. The Function URL is surfaced via
 *      `backend.addOutput({ custom: { leadIntakeUrl } })` in
 *      `amplify/backend.ts`.
 *
 * If neither is available, returns `undefined` and submitting the form
 * will surface an error to the user. Run `npx ampx sandbox` once to
 * generate the outputs file locally.
 */

let cached: string | null | undefined;

export async function getLeadIntakeUrl(): Promise<string | undefined> {
  if (cached !== undefined) return cached ?? undefined;

  const envUrl = import.meta.env.VITE_LEAD_INTAKE_URL as string | undefined;
  if (typeof envUrl === "string" && envUrl.length > 0) {
    cached = envUrl;
    return envUrl;
  }

  // `import.meta.glob` is the only build-safe way to optionally include
  // a generated file. If `amplify_outputs.json` doesn't exist yet (fresh
  // clone, no sandbox run), the glob returns an empty object and we
  // fall through to undefined.
  const candidates = import.meta.glob<{
    custom?: { leadIntakeUrl?: string };
  }>("/amplify_outputs.json", { import: "default" });
  const loader = candidates["/amplify_outputs.json"];
  if (loader) {
    try {
      const outputs = await loader();
      const url = outputs.custom?.leadIntakeUrl;
      if (typeof url === "string" && url.length > 0) {
        cached = url;
        return url;
      }
    } catch {
      // ignore — fall through to undefined
    }
  }

  cached = null;
  return undefined;
}

export type LeadPayload = {
  propertyType: "Association" | "Residential" | "Specialty";
  first: string;
  last: string;
  email: string;
  phone: string;
  addr: string;
  city: string;
  state: string;
  zip: string;
  sqft: string;
  units: string;
  freq: string;
  company: string;
  specialtyService?: string;
  specialtyPropertyType?: string;
};

export type LeadResponse =
  | {
      ok: true;
      upstream?: unknown;
      dryRun?: boolean;
      payload?: unknown;
      customerID?: number;
      subscriptionID?: number;
      agreementUrl?: string;
      monthlyCharge?: number;
      frequency?: string;
    }
  | { error: string; missing?: string[]; upstreamStatus?: number; upstreamBody?: unknown };

export async function submitLead(
  data: LeadPayload,
): Promise<{ ok: true; body: LeadResponse } | { ok: false; status: number; body: LeadResponse }> {
  const url = await getLeadIntakeUrl();
  if (!url) {
    return {
      ok: false,
      status: 0,
      body: {
        error:
          "Lead intake endpoint not configured. Run `npx ampx sandbox` or set VITE_LEAD_INTAKE_URL.",
      },
    };
  }

  const resp = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });

  let body: LeadResponse;
  try {
    body = (await resp.json()) as LeadResponse;
  } catch {
    body = { error: `Server returned non-JSON response (status ${resp.status})` };
  }

  if (resp.ok && "ok" in body && body.ok === true) {
    return { ok: true, body };
  }
  return { ok: false, status: resp.status, body };
}
