/**
 * Resolves the lead-intake Function URL.
 *
 * Order of resolution:
 *   1. `VITE_LEAD_INTAKE_URL` env var (set in `.env.local` or Amplify Hosting)
 *   2. `amplify_outputs.json` — generated by `npx ampx sandbox` or by an
 *      Amplify Hosting deploy. The Function URL is surfaced via
 *      `backend.addOutput({ custom: { leadIntakeUrl } })` in
 *      `amplify/backend.ts`.
 *
 * If neither is available, returns `undefined` and submitting the form
 * will surface an error to the user. Run `npx ampx sandbox` once to
 * generate the outputs file locally.
 */

let cached: string | null | undefined;

export async function getLeadIntakeUrl(): Promise<string | undefined> {
  if (cached !== undefined) return cached ?? undefined;

  const envUrl = import.meta.env.VITE_LEAD_INTAKE_URL as string | undefined;
  if (typeof envUrl === "string" && envUrl.length > 0) {
    cached = envUrl;
    return envUrl;
  }

  // `import.meta.glob` is the only build-safe way to optionally include
  // a generated file. If `amplify_outputs.json` doesn't exist yet (fresh
  // clone, no sandbox run), the glob returns an empty object and we
  // fall through to undefined.
  const candidates = import.meta.glob<{
    custom?: { leadIntakeUrl?: string };
  }>("/amplify_outputs.json", { import: "default" });
  const loader = candidates["/amplify_outputs.json"];
  if (loader) {
    try {
      const outputs = await loader();
      const url = outputs.custom?.leadIntakeUrl;
      if (typeof url === "string" && url.length > 0) {
        cached = url;
        return url;
      }
    } catch {
      // ignore — fall through to undefined
    }
  }

  cached = null;
  return undefined;
}

export type Attribution = {
  source?: string;
  medium?: string;
  campaign?: string;
  term?: string;
  content?: string;
  gclid?: string;
  referrer?: string;
  landingPage?: string;
};

export type LeadPayload = {
  propertyType: "Association" | "Residential" | "Specialty";
  first: string;
  last: string;
  email: string;
  phone: string;
  addr: string;
  city: string;
  state: string;
  zip: string;
  sqft: string;
  units: string;
  freq: string;
  company: string;
  specialtyService?: string;
  specialtyPropertyType?: string;
  /** Which form this came from, e.g. "contact" | "lp-call". */
  formId?: string;
  /** True only if the visitor actively ticked a consent control. */
  consentToContact?: boolean;
  /** The exact wording they agreed to, stored as consent evidence. */
  consentText?: string;
};

export type LeadResponse =
  | { ok: true; leadId: string }
  | { error: string; missing?: string[] };

const ATTRIBUTION_KEY = "bk_attribution";

/**
 * First-touch attribution. Captured on the landing page and kept for the
 * session, because the visitor usually submits from a different page than the
 * ad dropped them on — reading the URL at submit time would credit everything
 * to the form's own page.
 */
export function captureAttribution(): void {
  if (typeof window === "undefined") return;
  try {
    if (sessionStorage.getItem(ATTRIBUTION_KEY)) return;
    const q = new URLSearchParams(window.location.search);
    const a: Attribution = {
      source: q.get("utm_source") ?? undefined,
      medium: q.get("utm_medium") ?? undefined,
      campaign: q.get("utm_campaign") ?? undefined,
      term: q.get("utm_term") ?? undefined,
      content: q.get("utm_content") ?? undefined,
      gclid: q.get("gclid") ?? undefined,
      referrer: document.referrer || undefined,
      landingPage: window.location.pathname + window.location.search,
    };
    sessionStorage.setItem(ATTRIBUTION_KEY, JSON.stringify(a));
  } catch {
    // Private-mode / storage-disabled browsers still get to submit a lead.
  }
}

function readAttribution(): Attribution | undefined {
  if (typeof window === "undefined") return undefined;
  try {
    const raw = sessionStorage.getItem(ATTRIBUTION_KEY);
    return raw ? (JSON.parse(raw) as Attribution) : undefined;
  } catch {
    return undefined;
  }
}

export async function submitLead(
  data: LeadPayload,
): Promise<{ ok: true; body: LeadResponse } | { ok: false; status: number; body: LeadResponse }> {
  const url = await getLeadIntakeUrl();
  if (!url) {
    return {
      ok: false,
      status: 0,
      body: {
        error:
          "Lead intake endpoint not configured. Run `npx ampx sandbox` or set VITE_LEAD_INTAKE_URL.",
      },
    };
  }

  const resp = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...data, attribution: readAttribution() }),
  });

  let body: LeadResponse;
  try {
    body = (await resp.json()) as LeadResponse;
  } catch {
    body = { error: `Server returned non-JSON response (status ${resp.status})` };
  }

  if (resp.ok && "ok" in body && body.ok === true) {
    return { ok: true, body };
  }
  return { ok: false, status: resp.status, body };
}
